### ISSUE TITLE
nested asn1 error

### ISSUE THREAD

**Issue by osrufung** [quadion/iOSValidation#3]
./validateProvisioningProfile.rb:61:in `initialize': nested asn1 error (OpenSSL::X509::CertificateError)
    from ./validateProvisioningProfile.rb:61:in`new'
    from ./validateProvisioningProfile.rb:61:in `block in <main>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rexml/element.rb:905:in`block in each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rexml/xpath.rb:67:in `each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rexml/xpath.rb:67:in`each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rexml/element.rb:905:in `each'

**Comment by punksta** [comment]
@quadion It may be better to parse plist using gem _plist_?
[gist](https://gist.github.com/punksta/0468b0174659d86065ebff766cb89796)
